TOKEN = "5149101299:AAGEdvANcCfYNDnyUhrA6iCGBEHMUJJnoCc"
STICKERS=['CAACAgIAAxkBAAEE4EFilLs7WhW66oGlqAxUIwRxLjzX7AACTA8AAiKACUojeA481FiOlyQE',
          'CAACAgIAAxkBAAEE4DlilLrNbpvqMzyYFw_EzmCHypDCZQACCQAD8_KOPz0BzHWuifzlJAQ',
          'CAACAgQAAxkBAAEE4EVilLvBN6yOlizhtbualAEGaPihQgACUAEAAqghIQaxvfG1zemEoiQE',
          ]
STICKERS2=['CAACAgIAAxkBAAEE4I1ilNdnDlJ2hdMC85zAAhya5mY5tgACtwAD9wLID5Dxtgc7IUgdJAQ',
           'CAACAgIAAxkBAAEE4I9ilNeH-izxd5VulpY-VR9huBxlhQACSgADrWW8FIl7DV4Ij3qSJAQ',
           'CAACAgIAAxkBAAEE4JFilNe_D2RY9BiSzAggMTx1UGGhcQAC8gAD9wLID7_aPYqyARjKJAQ',
           'CAACAgIAAxkBAAEE4JNilNgjyKS1N-2cb4GzbKe5ZJnO8AACiQEAAiteUwt812TG6sLw9CQE',
           'CAACAgIAAxkBAAEE4JVilNhGb97dsq7eX2XPG-j0N2kFQgAC4wEAAladvQoPvIMqCGp2lSQE'
]
STICKERS3=[ 'CAACAgIAAxkBAAEE4KVilN7p_omL2ASuQ965FrZSBqKcsAACkgEAAladvQqf0C0IQi7VBSQE',
            'CAACAgIAAxkBAAEE4KdilN8kzB5hPlwFNyjrty6Jm7lcawACjg8AAg3GCEprgFmiFwjklyQE',
            'CAACAgIAAxkBAAEE4KlilN9LfR-mpyMaKc6_ZmlRSHg6TAACVAADQbVWDGq3-McIjQH6JAQ',
]
STICKERS4=[ 'CAACAgIAAxkBAAEE4N1ilQGU8N_T0pB8a5E1H6yh6fDh-wACvgAD9wLID2NpaQGUlw4kJAQ',
            'CAACAgIAAxkBAAEE4N9ilQGZwrNU5byvVpBpQJZh3Vuw1AACAgEAAjDUnREHq4uVsB20UiQE',
            'CAACAgIAAxkBAAEE4OFilQGhF__M4GQgb3qEVUtY-OjW7gACWAADQbVWDJmG_lj6IgQvJAQ',
            'CAACAgIAAxkBAAEE4ONilQGr8tklB23hwgIY13-31VFBHQACWgADwZxgDIo2CtyfZzcXJAQ'
]